### ISSUE TITLE
Decrease relation tagset

### ISSUE THREAD

**Issue by konstantinschulz** [konstantinschulz/german-covid-texts#1]
Constrain the relations tagset to a manageable amount (maybe 10 or 20?)

**Comment by MelinaPl** [comment]
View the list of 13 relation tags: https://github.com/konstantinschulz/german-covid-texts/wiki/Relation-Tags

**Comment by konstantinschulz** [comment]
Remarks by @MelinaPl :

- "P155": "follows" - unsure regarding match of Wikidata description and own example from sample texts
- Some of my examples from the sample texts do not include Named Entities (probably not the best examples), although we said that the layer of reference for relations should be the Named Entity level. Should we stick to the NE level?
