### ISSUE TITLE
Political Bias Annotation Questions

### ISSUE THREAD

**Issue by MelinaPl** [konstantinschulz/german-covid-texts#11]
- Difference center-right vs. far-right and center-left vs. far-left unclear

- Credibility annotations will only be conducted on filtered tweets that contain information. Will they be filtered for political bias as well? If not, what do we do with tweets where the content is somehow incomprehensible? Example:

    - @ Karl_Lauterbach geht es beim impfen nur ums impfen oder darum Antikörper zu produzieren ? ohne Antikörper Test wissen wir das doch nicht ! und generell kann man nie sagen wer schon vielleicht Antikörper hat man könnte Antikörper Test pro Quartal durchführen und danach impfe # Corona

- Solutions: Either annotate as “center” or add new label “incomprehensible”/ “unclear”

**Comment by konstantinschulz** [comment]
1. Good point, we will have to think about that. Maybe we need a list of typically very radical features, like conspiracy theories etc.? Then, we could identify anything that looks biased, but does not contain radical features, as center-left or center-right.
2. Is that example annotated as 1 segment, or multiple? I don't think it's incomprehensible if we allow coreference resolution. Then, we could label `geht es beim impfen nur ums impfen oder darum Antikörper zu produzieren ? ohne Antikörper Test wissen wir das doch nicht !` as center-right.
3. Using "center" as a fallback label sounds reasonable to me.

**Comment by MelinaPl** [comment]
1. https://github.com/konstantinschulz/german-covid-texts/wiki/Guidelines#differentiation-between-far-left-centre-left-and-far-right-centre-right
2. You are right, I just found the tweet initially confusing but it is comprehensible

**Comment by konstantinschulz** [comment]
Closing this for the time being, feel free to reopen if necessary
